# Generated by Django 5.2.6 on 2025-09-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="avatar",
            new_name="image",
        ),
    ]
