# Generated by Django 5.2.6 on 2025-09-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
