# Generated by Django 5.2.6 on 2025-09-17 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Введите дату создания",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
