# Generated by Django 5.2.6 on 2025-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_is_published_alter_blog_views_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Введите email адрес",
                max_length=254,
                null=True,
                verbose_name="Email адрес",
            ),
        ),
    ]
