# Generated by Django 5.2.6 on 2025-09-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="email",
            new_name="author_email",
        ),
    ]
