# Generated by Django 5.2.6 on 2025-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_email_blog_author_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author_email",
            field=models.EmailField(
                blank=True,
                default="hrustam911@mail.ru",
                help_text="Введите email адрес",
                max_length=254,
                null=True,
                verbose_name="Email адрес",
            ),
        ),
    ]
