# Generated by Django 5.2.6 on 2025-09-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contacts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={
                "ordering": ["name", "email"],
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
