# Generated by Django 5.2.6 on 2025-09-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_contacts_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={
                "ordering": ["name"],
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="email",
        ),
    ]
