# Generated by Django 5.2.6 on 2025-10-07 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_category_alter_product_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price"],
                "permissions": [("can_unpublish_product", "Отменить публикацию")],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Отметьте, если продукт должен быть опубликован",
                null=True,
                verbose_name="Опубликован",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
